import {uid,clone} from './core.js?v=2.0';
import {ctx,storyKey} from './bridge.js?v=2.0';
import {diagnostics} from './diagnostics.js?v=2.0';
export const defaultSocialRules=`群聊主要由当前加入的预设人格和User活跃。CHAR及其他NPC极少出没，不强迫参与，不轮流报到。允许零条消息、连续发言、互相引用、接梗、跑题与长期潜水。被@或拍一拍可以感知，不强制回应。按各自人格使用闺蜜深夜线上聊天语气，活泼或疗愈；直接聊刚才正文的高光、槽点及后续，不写分析报告。每句不超过15字，普通标点改为分泡，保留!/?/~/...等语气。用户请求行动选项时，遵循预设choice与状态栏：依次为日常、主线、恋爱、成人情境、搞笑、时间、两位预设人格如果是User共八类；前六个读者网名按本轮剧情重新构思，不沿用上一轮，不照抄示例；最后两位用对应预设人格名字。读者来信不是新群成员。`;
export function appendSystem(c,text,event={}){const m={id:uid(),side:'system',kind:'system',text,event,createdAt:Date.now(),status:'pending'};c.messages.push(m);c.updatedAt=m.createdAt;return m;}
export function messageContext(m,c){return {id:m.id,sender:m.side==='user'?'User':m.contactId||m.side,text:m.revoked?'撤回了一条消息':m.text,kind:m.kind||'text',replyTo:m.replyTo||null,quoted:m.replyTo?(()=>{const q=c.messages.find(x=>x.id===m.replyTo);return q?{id:q.id,text:q.revoked?'消息已撤回':q.text,sender:q.contactId||q.side}:null;})():null,mentions:m.mentions||[],event:m.event||null};}
export function socialMethods({esc,btn,field}){return {
 socialSettings(){const s=this.state.settings;this.modal('群聊规则',`<label class="shr-field">群聊规则<textarea name="socialRules" rows="12">${esc(s.socialRules||defaultSocialRules)}</textarea></label>${field('patSuffix','我的拍一拍后缀',s.patSuffix||'')}`,btn('soc:saveRules','保存','','shr-primary'));},
 async socialAction(a,id){const c=this.conversation(),m=c?.messages.find(x=>x.id===id);
 if(a==='settings')return this.socialSettings();
 if(a==='saveRules'){const v=this.values();this.state.settings.socialRules=v.socialRules;this.state.settings.patSuffix=v.patSuffix;await this.save();this.closeModal();return;}
 if(a==='menu'){if(!m||m.revoked)return;this.modal('消息',`<div class="shr-pre">${esc(m.text)}</div>`,btn('soc:quote','引用',id)+btn('soc:copy','复制',id)+btn('editChatMessage','编辑',id)+btn('soc:delete','删除',id)+(m.side==='user'?btn('soc:revoke','撤回',id):''));return;}
 if(a==='copy'){await navigator.clipboard.writeText(m.text);this.closeModal();return;}
 if(a==='quote'){c.replyTo=id;this.closeModal();this.render();this.root.querySelector('#shr-draft')?.focus();return;}
 if(a==='cancelQuote'){delete c.replyTo;this.render();return;}
 if(a==='locate'){const i=c.messages.findIndex(x=>x.id===id);if(i<0){this.status('原消息已删除或清理');return;}this.pageSize=Math.max(this.pageSize,c.messages.length-i);this.closeModal();this.render();const el=[...this.root.querySelectorAll('[data-message-id]')].find(e=>e.dataset.messageId===id);el?.scrollIntoView({block:'center'});el?.classList.add('shr-highlight');return;}
 if(a==='delete'||a==='revoke'){if(this.sending||this.gen.busy)throw Error('请等待生成完成');if(!m)return;if(a==='revoke'){m.revoked=true;m.text='撤回了一条消息';m.kind='system';m.side='system';m.status='pending';delete m.attachment;delete m.insertText;delete m.mentions;}else c.messages=c.messages.filter(x=>x.id!==id);await this.save();this.closeModal();this.render();return;}
 if(a==='at'){this.modal('@成员',c.members.map(x=>btn('soc:mention',esc(c.nicknames?.[x]||this.contact(x)?.name||'成员'),x)).join(''));return;}
 if(a==='mention'){if(!c.members.includes(id))return;c.draft=(c.draft||'')+'@'+(c.nicknames?.[id]||this.contact(id)?.name)+' ';c.draftMentions=[...new Set([...(c.draftMentions||[]),id])];this.closeModal();this.render();this.root.querySelector('#shr-draft')?.focus();return;}
 if(a==='pat'){const p=id==='user'?this.self():this.contact(id);if(!p||id!=='user'&&!c.members.includes(id))return;appendSystem(c,`${this.self().name}拍了拍${p.name}${id==='user'?this.state.settings.patSuffix||'':p.patSuffix||''}`,{type:'pat',target:id});await this.save();this.render();return;}
 if(a==='search'){this.modal('查找聊天记录','<input id="shr-history-search" placeholder="搜索消息"><div id="shr-history-results"></div>');return;}
 if(a==='leave'){if(this.sending)throw Error('请等待生成完成');appendSystem(c,`${this.self().name}退出了群聊`,{type:'leave',target:'user'});c.left=true;await this.save();this.groupPanel=false;this.render();return;}
 if(a==='details'){this.modal('群资料',field('title','群名称',c.title)+field('avatar','群头像网址',c.avatar||'')+btn('soc:groupAvatar','上传群头像')+field('announcement','群公告',c.announcement||'')+c.members.map((x,i)=>field('nick'+i,this.contact(x)?.name||'成员',c.nicknames?.[x]||'')).join(''),btn('soc:saveDetails','保存','','shr-primary'));return;}
 if(a==='groupAvatar'){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.onchange=async()=>{try{const file=input.files?.[0];if(!file)return;if(file.size>1024*1024)throw Error('请选择1MB以内的头像');const value=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const target=this.root.querySelector('[name=avatar]');if(target)target.value=value;}catch(e){this.error(e);}};input.click();return;}
 if(a==='saveDetails'){const v=this.values();if(v.title.trim()&&v.title!==c.title)appendSystem(c,`${this.self().name}将群名改为「${v.title.trim()}」`,{type:'rename'});if(v.announcement!==c.announcement)appendSystem(c,`${this.self().name}更新了群公告：${v.announcement}`,{type:'announcement'});c.title=v.title.trim()||c.title;if(v.avatar&&!/^(https?:\/\/|data:image\/(png|jpeg|webp);base64,)/i.test(v.avatar))throw Error('群头像地址不支持');c.avatar=v.avatar;c.announcement=v.announcement;c.nicknames=Object.fromEntries(c.members.map((x,i)=>[x,v['nick'+i]]));await this.save();this.closeModal();this.render();return;}
 if(a==='like'||a==='comment'||a==='replyComment'||a==='saveComment'){const items=this.state.worlds[storyKey()]?.moments.items||[];const post=items.find(x=>x.id===(a==='saveComment'?this.modalData.postId:a==='replyComment'?id.split('|')[0]:id));if(!post)return;
 if(a==='like'){post.likes ||= [];const key='user:'+this.self().name;const i=post.likes.findIndex(x=>x.id===key);if(i>=0)post.likes.splice(i,1);else post.likes.push({id:key,name:this.self().name});await this.save();this.render();return;}
 if(a==='saveComment'){const text=this.values().text.trim();if(!text)return;post.comments ||= [];post.comments.push({id:uid(),author:this.self().name,authorId:'user',text,replyTo:this.modalData.replyTo||null,createdAt:Date.now()});await this.save();this.closeModal();this.render();return;}
 this.modal('评论','<textarea name="text" rows="3" placeholder="评论"></textarea>',btn('soc:saveComment','发送','','shr-primary'),{postId:post.id,replyTo:a==='replyComment'?id.split('|')[1]:null});return;
 }
 },
 bindSocial(){let timer,start;this.root.addEventListener('contextmenu',e=>{const m=e.target.closest('[data-message-id]');if(m){e.preventDefault();this.socialAction('menu',m.dataset.messageId).catch(x=>this.error(x));}});this.root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;const m=e.target.closest('[data-message-id]');if(!m)return;start={x:e.clientX,y:e.clientY};timer=setTimeout(()=>{this.socialLongPress=true;this.socialAction('menu',m.dataset.messageId).catch(x=>this.error(x));},550);});this.root.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)clearTimeout(timer);});for(const name of ['pointerup','pointercancel'])this.root.addEventListener(name,()=>{clearTimeout(timer);start=null;});this.root.addEventListener('click',e=>{if(this.socialLongPress){this.socialLongPress=false;e.stopImmediatePropagation();e.preventDefault();}},true);this.root.addEventListener('dblclick',e=>{const a=e.target.closest('[data-pat]');if(a)this.socialAction('pat',a.dataset.pat).catch(x=>this.error(x));});this.root.addEventListener('input',e=>{if(e.target.id!=='shr-history-search')return;const q=e.target.value.trim().toLowerCase();this.root.querySelector('#shr-history-results').innerHTML=q?this.conversation().messages.filter(m=>m.text?.toLowerCase().includes(q)).map(m=>btn('soc:locate',esc(m.text),m.id)).join(''):'';});},
 renderSocialPost(i){return `<div class="shr-social-actions">${btn('soc:like',(i.likes||[]).some(x=>x.id==='user:'+this.self().name)?'取消赞':'赞',i.id)}${btn('soc:comment','评论',i.id)}</div><div class="shr-comments">${i.likes?.length?`<div>♡ ${i.likes.map(x=>esc(x.name)).join('、')}</div>`:''}${(i.comments||[]).map(x=>{const target=i.comments.find(y=>y.id===x.replyTo);return btn('soc:replyComment',`${esc(x.author)}${target?' 回复 '+esc(target.author):''}：${esc(x.text)}`,i.id+'|'+x.id);}).join('')}</div>`;},
};}
