import {ctx,storyKey,sourceMessages} from './bridge.js?v=2.0';
import {uid,digest,clone,parseJSON} from './core.js?v=2.0';
import {splitChatText} from './features.js?v=2.0';
import {defaultSocialRules} from './social.js?v=2.0';
import {diagnostics} from './diagnostics.js?v=2.0';
export function extractSocial(text){const matches=[...String(text).matchAll(/<shrimp_social>([\s\S]*?)<\/shrimp_social>/g)];if(!matches.length)return null;if(matches.length!==1)throw Error('本轮社交数据块重复，未清理正文');return {block:matches[0][0],data:parseJSON(matches[0][1])};}
export function validateSocial(data,conversations){if(!data||!Array.isArray(data.groups)||data.groups.length>30)throw Error('社交数据缺少groups');const out=[];for(const group of data.groups){const c=conversations.find(c=>c.id===group.conversationId&&!c.left);if(!c||!Array.isArray(group.messages)||group.messages.length>100)throw Error('社交群或消息列表无效');for(const row of group.messages){if(row.sender!=='user'&&!c.members.includes(row.sender))throw Error('社交消息包含非成员');if(typeof row.text!=='string'||!row.text.trim())throw Error('社交消息为空');for(const text of splitChatText(row.text))out.push({conversationId:c.id,message:{id:uid(),side:row.sender==='user'?'user':'ai',contactId:row.sender==='user'?'':row.sender,text,kind:'text',status:'sent',createdAt:Date.now(),storyGenerated:true}});}}return out;}
export function storySocialMethods({esc,btn}){return {
 async storySocialAction(a){if(a==='settings'){const s=this.state.settings.storySocial||{};this.modal('跟随正文发消息',`<label class="shr-check"><input type="checkbox" name="enabled" ${s.enabled?'checked':''}>开启同轮社交消息</label><p class="shr-note">随正文生成，不另发AI请求。规则可在群聊规则中编辑。请选择接收群聊。</p>${this.state.conversations.filter(c=>c.kind==='group'&&!c.left).map(c=>`<label class="shr-check"><input type="checkbox" name="targets" value="${esc(c.id)}" ${(s.targets||[]).includes(c.id)?'checked':''}>${esc(c.title)}</label>`).join('')}`,btn('story:save','保存','','shr-primary'));return;}
 if(a==='save'){const v=this.values(),targets=this.selected('targets');if(v.enabled&&!targets.length)throw Error('请选择至少一个群聊');this.state.settings.storySocial={enabled:v.enabled,targets};await this.save();await this.injectSocial('normal');this.closeModal();}}
 ,async injectSocial(type){const c=ctx(),set=c?.setExtensionPrompt;if(!set){if(this.state?.settings.storySocial?.enabled)throw Error('当前酒馆未提供前端提示词注入接口');return;}if(!this.state?.settings.storySocial?.enabled||this.gen.busy||['quiet','impersonate'].includes(type)){set('ame-shrimp-social','',1,0);return;}
 const targets=this.state.conversations.filter(x=>this.state.settings.storySocial.targets.includes(x.id)&&!x.left);const members=targets.map(x=>({conversationId:x.id,title:x.title,members:[{id:'user',name:c.name1},...x.members.map(id=>({id,name:this.contact(id)?.name,bio:this.contact(id)?.bio}))],history:x.messages.filter(m=>!m.sourceInactive).slice(-12).map(m=>({sender:m.side==='user'?'user':m.contactId,text:m.text}))}));
 const personality=targets.flatMap(g=>g.members.map(id=>this.contact(id))).filter(Boolean);const sourceIds=[...new Set(personality.map(m=>m.sourceId).filter(Boolean))];const sourceRules=sourceIds.flatMap(id=>{const source=this.state.sources[id];return source?sourceMessages(this.state,source,c.name1||'User',c.name2||'Char').map(m=>m.content):[];}).join('\n');
 const instruction=`在正常故事正文结束后，可以同时为鲜虾生成群聊消息。不改变正文写作要求，不额外扮演系统旁白。只在末尾输出一个<shrimp_social>{"groups":[{"conversationId":"群ID","messages":[{"sender":"成员ID或user","text":"消息"}]}]}</shrimp_social>。没有消息时groups为空数组。允许代User生成这里的群聊发言，用user标识；仅限此数据块。不要另输出status_app。${this.state.settings.socialRules||defaultSocialRules}\n成员预设参考（正文写作规则仍由原预设控制，此处只用于社交人格）：${sourceRules}\n接收群与最近聊天：${JSON.stringify(members)}`;
 set('ame-shrimp-social',instruction,1,0,false,0);diagnostics.log('social.inject',{count:targets.length});
 },
 bindStorySocial(){const c=ctx(),types=c.eventTypes||c.event_types||{};globalThis.ameShrimpSocialInterceptor=async(chat,size,abort,type)=>this.injectSocial(type);const run=()=>{this.socialChain=(this.socialChain||Promise.resolve()).catch(()=>{}).then(()=>this.receiveSocial()).catch(e=>{diagnostics.log('social.failure',{stage:'receive',errorType:e.name});this.error(e);});};for(const n of ['GENERATION_ENDED','MESSAGE_RECEIVED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_DELETED','CHAT_CHANGED'])if(types[n])c.eventSource.on(types[n],run);if(types.GENERATION_STOPPED)c.eventSource.on(types.GENERATION_STOPPED,()=>c.setExtensionPrompt?.('ame-shrimp-social','',1,0));this.injectSocial('normal').catch(e=>this.error(e));},
 async receiveSocial(){if(!this.state?.settings.storySocial?.enabled||this.mainBusy||this.gen.busy)return;const c=ctx(),key=storyKey();if(!key)return;const receipts=this.state.socialReceipts ||= {};let changed=false;
 for(let index=0;index<c.chat.length;index++){const m=c.chat[index];if(m.is_user||m.is_system)continue;const extracted=extractSocial(m.mes);if(!extracted)continue;m.extra ||= {};m.extra.shrimpSocial ||= {id:uid(),versions:{}};const id=await digest([key,index,m.swipe_id||0,extracted.block]);diagnostics.log('social.parse',{id,count:index});
 const allowed=this.state.conversations.filter(x=>(this.state.settings.storySocial.targets||[]).includes(x.id));const rows=validateSocial(extracted.data,allowed);const version=m.swipe_id||0; m.extra ||= {};m.extra.shrimpSocial ||= {id:uid(),versions:{}};
 // Receipt and messages are durably saved before any source text is removed.
 const previous=receipts[id];if(!previous){for(const row of rows){const target=this.state.conversations.find(x=>x.id===row.conversationId);target.messages.push({...row.message,sourceReceipt:id});if(!(this.visible&&this.tab==='chats'&&this.conversation()?.id===target.id))target.unread=(target.unread||0)+1;target.updatedAt=Date.now();}receipts[id]={key,messageId:m.extra.shrimpSocial.id,swipe:version,createdAt:Date.now()};}
 try{await this.save();}catch(e){if(!previous){for(const target of this.state.conversations)target.messages=target.messages.filter(x=>x.sourceReceipt!==id);delete receipts[id];}throw e;}
 if(storyKey()!==key||c.chat[index]!==m)throw Error('故事已切换，原文未清理');if(!String(m.mes).includes(extracted.block))continue;
 const before=m.mes,swipeBefore=m.swipes?.[version];m.mes=before.replace(extracted.block,'');if(m.swipes&&m.swipes[version]===before)m.swipes[version]=m.mes;m.extra.shrimpSocial.versions[version]=id;if(m.swipe_info?.[version])m.swipe_info[version].extra=clone(m.extra);
 try{if(typeof c.saveChat!=='function')throw Error('酒馆保存接口不可用');await c.saveChat();c.updateMessageBlock?.(index,m,{rerenderMessage:true});diagnostics.log('social.cleaned',{id,count:rows.length});}catch(e){m.mes=before;if(m.swipes)m.swipes[version]=swipeBefore;diagnostics.log('social.cleanup_failed',{id});throw e;}changed=true;
 }
 const active=new Set(c.chat.map(m=>m.extra?.shrimpSocial?.versions?.[m.swipe_id||0]).filter(Boolean));for(const conv of this.state.conversations)for(const m of conv.messages){if(m.sourceReceipt&&receipts[m.sourceReceipt]?.key===key){const inactive=!active.has(m.sourceReceipt);if(!!m.sourceInactive!==inactive){m.sourceInactive=inactive;changed=true;}}}
 if(changed){await this.save();if(this.visible&&!this.root.querySelector('.shr-modal'))this.render();}
 }
};}
