import {uid} from './core.js?v=2.0';
import {diagnostics} from './diagnostics.js?v=2.0';
export function decodeBook(content){const bytes=Uint8Array.from(atob(content),c=>c.charCodeAt(0));try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{return new TextDecoder('gb18030').decode(bytes);}}
export function txtMethods({esc,btn}){return {
 async txtOpen(key){const r=this.readingRow(key);this.txtText=decodeBook(r.content);this.txtKey=key;this.txtPage=Math.max(0,Math.min(Math.round((r.progress||0)*Math.max(0,Math.ceil(this.txtText.length/4000)-1)),Math.max(0,Math.ceil(this.txtText.length/4000)-1)));this.render();diagnostics.log('reading.txt.open',{characters:this.txtText.length});},
 txtRender(){const r=this.readingRow(this.txtKey),pages=Math.max(1,Math.ceil(this.txtText.length/4000));return `<main class="shr-wide shr-txt">${this.header(r.title,btn('rd:txtExit','书架'))}<div class="shr-scroll shr-txt-body" data-txt-text>${esc(this.txtText.slice(this.txtPage*4000,(this.txtPage+1)*4000))}</div><div class="shr-txt-actions">${btn('rd:txtPrev','上一页')}<small>${this.txtPage+1} / ${pages}</small>${btn('rd:txtNext','下一页')}${btn('rd:txtExcerpt','摘抄选中文字')}</div></main>`;},
 async txtAction(a){if(!this.txtKey)return;const r=this.readingRow(this.txtKey),pages=Math.max(1,Math.ceil(this.txtText.length/4000));if(a==='txtExcerpt'){const selection=window.getSelection(),body=this.root.querySelector('[data-txt-text]');if(!selection?.rangeCount||!body?.contains(selection.anchorNode)||!body.contains(selection.focusNode)||!selection.toString().trim())throw Error('先在正文中选中文字');const text=selection.toString().trim();await this.reading.put('tavern',{id:uid(),kind:'excerpt',text,source:r.title,chapter:`第 ${this.txtPage+1} 页`,note:'',group:r.group||'',createdAt:Date.now(),bookId:r.id});this.status('摘抄已保存到酒馆账户');selection.removeAllRanges();diagnostics.log('reading.txt.excerpt',{characters:text.length});return;}
 if(a==='txtPrev')this.txtPage=Math.max(0,this.txtPage-1);if(a==='txtNext')this.txtPage=Math.min(pages-1,this.txtPage+1);
 await this.reading.put(r.place,{...r,progress:pages===1?1:this.txtPage/(pages-1),lastRead:Date.now()});if(a==='txtExit'){this.txtKey=null;this.txtText='';}this.render();}
};}
