import test from 'node:test';
import assert from 'node:assert/strict';
import {apiEndpoint,fetchModels,fishboardStyles,currentCharacter} from '../chat-integration.js';
import {chatProtocol,upgradeFeatures} from '../features.js';
import {freshState} from '../core.js';
test('模型地址规范化及读取去重，不发送聊天补全请求',async()=>{assert.equal(apiEndpoint('https://example.com/provider/v1/chat/completions','models'),'https://example.com/provider/v1/models');const old=globalThis.fetch;let requested;globalThis.fetch=async(url,opts)=>{requested={url,opts};return new Response(JSON.stringify({data:[{id:'model-b'},{id:'model-a'},{id:'model-b'}]}));};try{assert.deepEqual(await fetchModels('https://example.com/v1','secret'),['model-a','model-b']);assert.equal(requested.url,'https://example.com/v1/models');assert.equal(requested.opts.headers.Authorization,'Bearer secret');}finally{globalThis.fetch=old;}});
test('读取鱼板面当前存储，不把旧缓存混入有效文风库，不写入',()=>{const old=globalThis.window,ls=globalThis.localStorage;let writes=0;const data={'ame-style-management-v05':JSON.stringify({styles:[{id:'old',name:'旧缓存',content:'旧'}]})};globalThis.localStorage={getItem:k=>data[k]||null,setItem:()=>writes++};globalThis.window={TavernHelper:{getVariables:()=>({'鲜虾鱼板面.data.v1':{styles:[{id:'live',name:'文风',content:'全文',note:'注'}]}})},SillyTavern:{getContext:()=>({})}};try{assert.deepEqual(fishboardStyles().map(s=>s.id),['live']);data['ame-style-management-v05_storage_choice_v1']='browser';assert.deepEqual(fishboardStyles().map(s=>s.id),['old']);data['鲜虾鱼板面.retiredCopies.v1']=JSON.stringify({'ame-style-management-v05':true});assert.deepEqual(fishboardStyles(),[]);assert.equal(writes,0);}finally{globalThis.window=old;globalThis.localStorage=ls;}});
test('当前角色依据酒馆角色ID而非名字，头像使用角色文件',()=>{const old=globalThis.window;globalThis.window={SillyTavern:{getContext:()=>({characterId:1,characters:[{name:'同名',avatar:'one.png'},{name:'同名',avatar:'two.png'}],getThumbnailUrl:(type,file)=>`/thumbnail?type=${type}&file=${file}`})}};try{assert.equal(currentCharacter().id,'two.png');assert.match(currentCharacter().avatar,/two.png/);}finally{globalThis.window=old;}});
test('升级清除旧模式控制；协议要求聊天对象口吻与预设功能',()=>{const s=freshState();s.conversations=[{messages:[{text:'旧消息'}],features:{mode:'choices',floor:2,readStory:false}}];upgradeFeatures(s);assert.deepEqual(s.conversations[0].features,{readStory:true});assert.equal(s.conversations[0].messages[0].text,'旧消息');const p=chatProtocol('chat',{},[{id:'a',name:'Ako'}],'User');assert.match(p,/成员本人口吻/);assert.match(p,/预设中对应功能/);assert.doesNotMatch(p,/默认 8 条|日常生活发展选项/);});
