import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(require.resolve('playwright', { paths: [process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES || process.cwd()] }));
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
let stored = null, readingStored = null, failReading = false;
const fixture = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/fonts/400.css"><style>#shrimp-app{font-family:"Noto Sans SC",sans-serif}</style></head><body><div id="extensionsMenu"></div><button id="send_but" onclick="window.sent=(window.sent||0)+1">send</button><textarea id="send_textarea"></textarea><script>
window.calls=[];window.failNext=false;window.notices=[];window.listeners={};window.toastr={error:x=>notices.push(x)};
const preset={prompts:[{identifier:'persona',name:'Ako人格',content:'你是Ako，一个爱聊天的诗人。'},{identifier:'off',name:'conversation关闭条目',content:'绝不执行我'},{identifier:'loose',name:'未链接',content:'不执行孤立条目'},{identifier:'choices',name:'行动选项条目',content:'{{setvar::choice::根据 [群聊状态栏]生成行动选项}} {{getvar::choice}}'}],prompt_order:[{character_id:100001,order:[{identifier:'persona',enabled:true},{identifier:'off',enabled:false},{identifier:'choices',enabled:false}]}]};
window.preset=preset;window.originalPreset=JSON.stringify(preset);
const c={name1:'Ameki',name2:'叶知微',characterId:0,chatId:'story-one',groupId:null,characters:[{name:'叶知微',avatar:'ye.png',description:'药王谷医者',data:{description:'药王谷医者',extensions:{world:'谷中日常'}}}],chat:[{name:'叶知微',mes:'今日城南开了新茶铺。',is_user:false}],powerUserSettings:{persona_description:'旅人'},chatMetadata:{},extensionSettings:{},getRequestHeaders:()=>({'Content-Type':'application/json'}),getThumbnailUrl:()=>'',getCurrentChatId:()=>c.chatId,eventTypes:{GENERATION_STARTED:'start',GENERATION_ENDED:'end',GENERATION_STOPPED:'stop',MESSAGE_RECEIVED:'received',CHARACTER_MESSAGE_RENDERED:'render',MESSAGE_EDITED:'edit',MESSAGE_DELETED:'delete',CHAT_CHANGED:'chat',APP_READY:'ready'},eventSource:{on:(n,f)=>(listeners[n]||=[]).push(f)},getPresetManager:()=>({getPresetList:()=>({preset_names:{'Ako 1.92':0,'Ako 1.93':1}}),getSelectedPresetName:()=> 'Ako 1.92',getCompletionPresetByName:name=>name==='Ako 1.93'?{...structuredClone(preset),model:'v2'}:preset}),generateRaw:async ({prompt})=>{calls.push(prompt);await new Promise(r=>setTimeout(r,80));if(failNext){failNext=false;throw Error('模拟断网');}const sys=prompt.find(p=>p.content.includes('成员：'));if(sys){const members=JSON.parse(sys.content.split('成员：')[1]);const last=JSON.parse([...prompt].reverse().find(p=>p.role==='user').content);if(sys.content.includes('当前是持续的选项模式') && !last.text?.includes('先讨论')) return JSON.stringify({messages:[{contactId:members[0].contactId,kind:'text',text:'先看看这两种走法'},{contactId:members[0].contactId,kind:'option',reader:'栗子er',optionType:'日常生活发展选项',text:'我走进茶馆，要了一壶热茶。'},{contactId:members[0].contactId,kind:'option',reader:'Ako',optionType:'ako如果是User选项',text:'我在门前停下，问掌柜今日有什么点心。'}]});if(last.text?.includes('推荐'))return JSON.stringify({messages:[{contactId:members[0].contactId,kind:'publisher',text:'这家号就爱找街边小店',publisher:{name:'巷口吃什麼',intro:'帶你看看當地街邊小店',topics:'美食、街边小吃、平价探店',style:'活泼亲切，像朋友推荐好吃的小店',script:'simplified'}}]});return JSON.stringify({messages:[{contactId:members[0].contactId,text:'我想听你说。'},{contactId:members[0].contactId,text:'慢慢聊，不着急。'}]});}if(prompt[0].content.includes('资料提取器'))return JSON.stringify({people:[{name:'Ako',bio:'我爱写诗，也爱聊天。',evidence:[{id:'persona',quote:'你是Ako，一个爱聊天的诗人。'}]}]});const pubs=JSON.parse(prompt[1].content).subscribedPublishers;if(pubs)return JSON.stringify({items:pubs.map(p=>({publisherId:p.id,title:'燒鵝店開張',summary:'街坊又有新去處',body:'城南新店開門迎客，街坊前來試味。記者走訪小店，見店中茶香四溢，招牌燒鵝剛剛出爐。掌櫃表示，鋪面雖小，食材都是清早挑選，不求花巧，只盼客人吃得稱心。門前排隊的食客有熟面孔，也有路過的新客。有街坊說，好不好吃，終究還要自己試過才知，消息尚待更多回應。'}))});return JSON.stringify({items:[{author:'城南茶馆',title:'今日新茶',body:'店门开了，第一壶茶已经沏好。'}]});}};
window.context=c;window.emit=(n,...a)=>Promise.all((listeners[n]||[]).map(f=>f(...a)));window.SillyTavern={getContext:()=>c};
</script><script type="module" src="/index.js"></script></body></html>`;
const server = createServer(async (req, res) => {
    const path = new URL(req.url, 'http://localhost').pathname;
    if (path.startsWith('/fonts/') && process.env.SHRIMP_TEST_FONTS) { try {res.setHeader('Content-Type',path.endsWith('.css')?'text/css':'font/woff2');return res.end(await readFile(resolve(process.env.SHRIMP_TEST_FONTS, path.slice(7))));}catch{res.statusCode=404;return res.end();}}
    if (path === '/api/users/me') {res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({handle:'reader-test'}));}
    if(path === '/user/files/ame-shrimp-reading-v1.json'){res.statusCode=readingStored?200:404;res.setHeader('Content-Type','application/json');return res.end(readingStored||'{}');}
    if (path === '/') { res.setHeader('Content-Type', 'text/html'); return res.end(fixture); }
    if (path === '/script.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end('export const isGenerating=()=>false;'); }
    if (path === '/scripts/world-info.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end('export const selected_world_info=[];export const world_info={};export const loadWorldInfo=async()=>({entries:{one:{content:"城南是一座寻常小城。",comment:"地理",disable:false}}});'); }
    if (path === '/user/files/ame-shrimp-v1.json') { res.setHeader('Content-Type', 'application/json'); res.statusCode = stored ? 200 : 404; return res.end(stored || '{}'); }
    if (path === '/api/files/upload') { let b='';for await(const part of req)b+=part;const payload=JSON.parse(b);if(payload.name==='ame-shrimp-reading-v1.json'){if(failReading){res.statusCode=500;return res.end('{}');}readingStored=Buffer.from(payload.data,'base64').toString();}else stored=Buffer.from(payload.data,'base64').toString();res.setHeader('Content-Type','application/json');return res.end('{"path":"user/files/ame-shrimp-v1.json"}'); }
    try { res.setHeader('Content-Type', path.endsWith('.css') ? 'text/css' : 'text/javascript'); res.end(await readFile(resolve(root, '.' + path))); } catch { res.statusCode=404;res.end(); }
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser = await chromium.launch({ headless: true, ...(process.env.SHRIMP_CHROMIUM ? {executablePath:process.env.SHRIMP_CHROMIUM} : {}), args: ['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'], timeout: 20000 });
const base = `http://127.0.0.1:${server.address().port}`;
const page=await browser.newPage({viewport:{width:390,height:844}});
page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async(a,id)=>{const sel=`[data-action="${a}"]${id?`[data-id="${id}"]`:''}:visible`;const m=page.locator('.shr-modal '+sel);await (await m.count()?m:page.locator(sel)).first().click();};
const done=()=>page.locator('.shr-modal').waitFor({state:'detached'});
try{
 await page.goto(base);await page.locator('#shrimp-launcher').click();await click('tab','reading');await page.locator('.shr-reading').waitFor();
 await click('rd:import');await page.locator('[name=readingFiles]').setInputFiles([{name:'江湖随笔.txt',mimeType:'text/plain',buffer:Buffer.from('江湖很远。\n茶还热着。')},{name:'文学札记.docx',mimeType:'application/octet-stream',buffer:Buffer.from('example-original-bytes')},{name:'山海记.epub',mimeType:'application/epub+zip',buffer:Buffer.from('example-original-bytes-2')}]);await page.locator('[name=group]').fill('常读');await click('rd:importSave');await done();assert.equal(await page.locator('.shr-reading-item').count(),3);assert.equal(readingStored,null);
 await page.screenshot({path:resolve(root,'../mobile-bookshelf-v1.2.png')});
 await click('rd:organize');await click('rd:all');await click('rd:move','tavern');await click('rd:moveSave');await done();assert.equal(JSON.parse(readingStored).items.length,3);assert.equal(await page.locator('[data-reading-place=browser]').count(),0);
 await page.reload();await page.locator('#shrimp-launcher').click();await click('tab','reading');await page.locator('.shr-reading').waitFor();assert.equal(await page.locator('.shr-reading-item').count(),3);
 await click('rd:kind','excerpt');await click('rd:import');await page.locator('[name=readingFiles]').setInputFiles({name:'摘抄.txt',mimeType:'text/plain',buffer:Buffer.from('\uFEFF今朝恩仇一杯酒\r\n\r\n莫念他日山高水远难重逢\n')});await page.locator('[name=place]').selectOption('tavern');await click('rd:importSave');await done();assert.equal(await page.locator('.shr-reading-item').count(),2);
 await click('rd:item');await page.locator('[name=note]').fill('我的读书笔记');await page.locator('[name=source]').fill('江湖随笔');await page.locator('[name=chapter]').fill('第一章');await click('rd:excerptSave');await done();
 await page.screenshot({path:resolve(root,'../mobile-excerpts-v1.2.png')});
 const downloadPromise=page.waitForEvent('download');await click('rd:export');const download=await downloadPromise;const data=await readFile(await download.path(),'utf8');assert.equal(data,'今朝恩仇一杯酒\n莫念他日山高水远难重逢');assert.equal(data.includes('我的读书笔记'),false);
 await click('rd:organize');await click('rd:all');await click('rd:move','browser');await click('rd:moveSave');await done();assert.equal(JSON.parse(readingStored).items.filter(x=>x.kind==='excerpt').length,0);assert.equal(await page.locator('[data-reading-place=browser]').count(),2);
 // New browser context sees only Tavern books, no browser-local excerpts.
 const other=await browser.newPage();await other.goto(base);await other.locator('#shrimp-launcher').click();await other.locator('[data-action=tab][data-id=reading]').click();await other.locator('.shr-reading').waitFor();assert.equal(await other.locator('.shr-reading-item').count(),3);await other.locator('[data-action="rd:kind"][data-id=excerpt]').click();assert.equal(await other.locator('.shr-reading-item').count(),0);await other.close();
 // Failed remote write preserves the local excerpt and the modal.
 await click('rd:all');await click('rd:move','tavern');failReading=true;await click('rd:moveSave');await page.waitForFunction(()=>document.querySelector('.shr-status').textContent.includes('保存失败'));assert.equal(await page.locator('.shr-modal').count(),1);assert.equal(await page.locator('[data-reading-place=browser]').count(),2);failReading=false;await click('rd:moveSave');await done();assert.equal(JSON.parse(readingStored).items.filter(x=>x.kind==='excerpt').length,2);
 await click('rd:all');await click('rd:delete');await click('rd:deleteSave');await done();assert.equal(await page.locator('.shr-reading-item').count(),0);assert.equal(JSON.parse(readingStored).items.filter(x=>x.kind==='book').length,3);
 assert.deepEqual(errors,[]);console.log('PASS: bookshelf imports, batch migrations, original cleanup, reload, device isolation, TXT roundtrip, notes, failure retry, excerpt deletion');
}catch(e){await page.screenshot({path:resolve(root,'../reading-failed.png')});throw e;}finally{await browser.close();server.close();}
