import test from 'node:test';
import assert from 'node:assert/strict';
import {ReadingRepository,emptyLibrary,excerptLines,exportExcerpts,bookFromFile} from '../reading-store.js';
class Memory {constructor(){this.data=emptyLibrary();}async read(){return structuredClone(this.data);}async write(d,e){if(this.fail)throw Error('保存失败');assert.equal(this.data.revision,e);this.data=structuredClone(d);if(this.corrupt)this.data.items=[];}}
const setup=async()=>{const a=new Memory(),b=new Memory(),repo=new ReadingRepository(a,b);await repo.load();return {a,b,repo};};
const row={id:'book1',kind:'book',title:'测试',content:'YWJj',progress:0.35,annotations:[{text:'摘句',note:'备注'}]};
test('迁移完整核对后删除原记录，阅读数据一起保留，独立摘抄不移动',async()=>{const {repo,a,b}=await setup();await repo.put('tavern',row);await repo.put('tavern',{id:'excerpt1',kind:'excerpt',text:'另一条'});await repo.move('tavern','browser','book1');assert.deepEqual(a.data.items,[row]);assert.equal(b.data.items.length,1);assert.equal(b.data.items[0].id,'excerpt1');await repo.move('browser','tavern','book1');assert.equal(a.data.items.length,0);assert.deepEqual(b.data.items.at(-1),row);});
test('目标保存失败或回读不一致不删除原件',async()=>{const {repo,a,b}=await setup();await repo.put('tavern',row);a.fail=true;await assert.rejects(repo.move('tavern','browser','book1'));assert.deepEqual(b.data.items,[row]);a.fail=false;a.corrupt=true;await assert.rejects(repo.move('tavern','browser','book1'));assert.deepEqual(b.data.items,[row]);});
test('源删除失败可重试迁移，不重复生成目标记录',async()=>{const {repo,a,b}=await setup();await repo.put('tavern',row);b.fail=true;await assert.rejects(repo.move('tavern','browser','book1'));assert.equal(a.data.items.length,1);assert.equal(b.data.items.length,1);b.fail=false;await repo.move('tavern','browser','book1');assert.equal(a.data.items.length,1);assert.equal(b.data.items.length,0);});
test('目标有不同版本时不覆盖任何一边',async()=>{const {repo,a,b}=await setup();await repo.put('tavern',row);await repo.put('browser',{...row,title:'其他版本'});await assert.rejects(repo.move('tavern','browser',row.id));assert.equal(a.data.items[0].title,'其他版本');assert.equal(b.data.items[0].title,'测试');});
test('TXT 一行一条，空行忽略，导出不混入笔记和出处',()=>{assert.deepEqual(excerptLines('\uFEFF一\r\n\r\n二\n三'),['一','二','三']);assert.equal(exportExcerpts([{text:'第一\n条',note:'不导出',source:'出处'},{text:'第二条'}]),'第一 条\n第二条');});
test('原书文件往返保持字节与名称',async()=>{const bytes=new Uint8Array([0,255,100,22]);const f=new File([bytes],'样本.epub');const r=await bookFromFile(f);assert.equal(r.filename,'样本.epub');assert.deepEqual(Uint8Array.from(atob(r.content),c=>c.charCodeAt(0)),bytes);assert.equal(r.kind,'book');});
