import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(require.resolve('playwright', { paths: [process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES || process.cwd()] }));
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
let stored = null, modelRequests = 0;
const fixture = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/fonts/400.css"><style>#shrimp-app{font-family:"Noto Sans SC",sans-serif}</style></head><body><div id="extensionsMenu"></div><button id="send_but" onclick="window.sent=(window.sent||0)+1">send</button><textarea id="send_textarea"></textarea><script>
window.calls=[];window.failNext=false;window.notices=[];window.listeners={};window.toastr={error:x=>notices.push(x)};
const preset={prompts:[{identifier:'persona',name:'Ako人格',content:'你是Ako，一个爱聊天的诗人。'},{identifier:'off',name:'conversation关闭条目',content:'绝不执行我'},{identifier:'loose',name:'未链接',content:'不执行孤立条目'},{identifier:'choices',name:'行动选项条目',content:'{{setvar::choice::根据 [群聊状态栏]生成行动选项}} {{getvar::choice}}'}],prompt_order:[{character_id:100001,order:[{identifier:'persona',enabled:true},{identifier:'off',enabled:false},{identifier:'choices',enabled:false}]}]};
window.preset=preset;window.originalPreset=JSON.stringify(preset);
const c={name1:'Ameki',name2:'叶知微',characterId:0,chatId:'story-one',groupId:null,characters:[{name:'叶知微',avatar:'ye.png',description:'药王谷医者',data:{description:'药王谷医者',extensions:{world:'谷中日常'}}}],chat:[{name:'叶知微',mes:'今日城南开了新茶铺。',is_user:false}],powerUserSettings:{persona_description:'旅人'},chatMetadata:{},extensionSettings:{},getRequestHeaders:()=>({'Content-Type':'application/json'}),getThumbnailUrl:()=>'',getCurrentChatId:()=>c.chatId,eventTypes:{GENERATION_STARTED:'start',GENERATION_ENDED:'end',GENERATION_STOPPED:'stop',MESSAGE_RECEIVED:'received',CHARACTER_MESSAGE_RENDERED:'render',MESSAGE_EDITED:'edit',MESSAGE_DELETED:'delete',CHAT_CHANGED:'chat',APP_READY:'ready'},eventSource:{on:(n,f)=>(listeners[n]||=[]).push(f)},getPresetManager:()=>({getPresetList:()=>({preset_names:{'Ako 1.92':0,'Ako 1.93':1}}),getSelectedPresetName:()=> 'Ako 1.92',getCompletionPresetByName:name=>name==='Ako 1.93'?{...structuredClone(preset),model:'v2'}:preset}),generateRaw:async ({prompt})=>{calls.push(prompt);await new Promise(r=>setTimeout(r,80));if(failNext){failNext=false;throw Error('模拟断网');}const sys=prompt.find(p=>p.content.includes('成员：'));if(sys){const members=JSON.parse(sys.content.split('成员：')[1]);const last=JSON.parse([...prompt].reverse().find(p=>p.role==='user').content);if(last.text?.includes('选项')) return JSON.stringify({messages:[{contactId:members[0].contactId,kind:'text',text:'先看看这两种走法'},{contactId:members[0].contactId,kind:'option',text:'要不先进去喝口茶？走了半天也该歇歇啦',insertText:'我走进茶馆，要了一壶热茶。'},{contactId:members[0].contactId,kind:'option',text:'我倒想先问问掌柜　今日做了什么点心',insertText:'我在门前停下，问掌柜今日有什么点心。'}]});if(last.text?.includes('文风'))return JSON.stringify({messages:[{contactId:members[0].contactId,kind:'style',styleId:'style-live',text:'这一篇的轻巧劲儿，我觉得很合适。'}]});if(last.text?.includes('推荐'))return JSON.stringify({messages:[{contactId:members[0].contactId,kind:'publisher',text:'这家号就爱找街边小店',publisher:{name:'巷口吃什麼',intro:'帶你看看當地街邊小店',topics:'美食、街边小吃、平价探店',style:'活泼亲切，像朋友推荐好吃的小店',script:'simplified'}}]});return JSON.stringify({messages:[{contactId:members[0].contactId,text:'我想听你说。'},{contactId:members[0].contactId,text:'慢慢聊，不着急。'}]});}if(prompt[0].content.includes('资料提取器'))return JSON.stringify({people:[{name:'Ako',bio:'我爱写诗，也爱聊天。',evidence:[{id:'persona',quote:'你是Ako，一个爱聊天的诗人。'}]}]});const pubs=JSON.parse(prompt.at(-1).content).subscribedPublishers;if(pubs)return JSON.stringify({items:pubs.map(p=>({publisherId:p.id,title:'燒鵝店開張',summary:'街坊又有新去處',body:'城南新店開門迎客，街坊前來試味。記者走訪小店，見店中茶香四溢，招牌燒鵝剛剛出爐。掌櫃表示，鋪面雖小，食材都是清早挑選，不求花巧，只盼客人吃得稱心。門前排隊的食客有熟面孔，也有路過的新客。有街坊說，好不好吃，終究還要自己試過才知，消息尚待更多回應。'}))});return JSON.stringify({items:[{author:'城南茶馆',title:'今日新茶',body:'店门开了，第一壶茶已经沏好。'}]});}};
window.fish={styles:[{id:'style-live',name:'爱情小调',content:'来自鱼板面的完整文风正文',note:'轻盈生活化',author:'Ameki'}]};window.fishOriginal=JSON.stringify(window.fish);window.TavernHelper={getVariables:()=>({'鲜虾鱼板面.data.v1':window.fish})};window.context=c;window.emit=(n,...a)=>Promise.all((listeners[n]||[]).map(f=>f(...a)));window.SillyTavern={getContext:()=>c};
</script><script type="module" src="/index.js"></script></body></html>`;
const server = createServer(async (req, res) => {
    const path = new URL(req.url, 'http://localhost').pathname;
    if (path.startsWith('/fonts/') && process.env.SHRIMP_TEST_FONTS) { try {res.setHeader('Content-Type',path.endsWith('.css')?'text/css':'font/woff2');return res.end(await readFile(resolve(process.env.SHRIMP_TEST_FONTS, path.slice(7))));}catch{res.statusCode=404;return res.end();}}
    if(path==='/models'){modelRequests++;res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({data:[{id:'model-a'},{id:'model-b'}]}));}
    if(path==='/thumbnail'){res.setHeader('Content-Type','image/svg+xml');return res.end('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="80" height="80" fill="#879eaa"/><circle cx="40" cy="30" r="15" fill="#f2e6d0"/><path d="M10 80 Q40 25 70 80" fill="#e3ded3"/></svg>');}
    if (path === '/') { res.setHeader('Content-Type', 'text/html'); return res.end(fixture); }
    if (path === '/script.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end('export const isGenerating=()=>false;'); }
    if (path === '/scripts/world-info.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end('export const selected_world_info=[];export const world_info={};export const loadWorldInfo=async()=>({entries:{one:{content:"城南是一座寻常小城。",comment:"地理",disable:false}}});'); }
    if (path === '/user/files/ame-shrimp-v1.json') { res.setHeader('Content-Type', 'application/json'); res.statusCode = stored ? 200 : 404; return res.end(stored || '{}'); }
    if (path === '/api/files/upload') { let b='';for await(const part of req)b+=part;stored=Buffer.from(JSON.parse(b).data,'base64').toString();res.setHeader('Content-Type','application/json');return res.end('{"path":"user/files/ame-shrimp-v1.json"}'); }
    try { res.setHeader('Content-Type', path.endsWith('.css') ? 'text/css' : 'text/javascript'); res.end(await readFile(resolve(root, '.' + path))); } catch { res.statusCode=404;res.end(); }
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser = await chromium.launch({ headless: true, ...(process.env.SHRIMP_CHROMIUM ? {executablePath:process.env.SHRIMP_CHROMIUM} : {}), args: ['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'], timeout: 20000 });
const base = `http://127.0.0.1:${server.address().port}`;
const page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(12000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const click=async(a,id)=>{console.log('click',a,id||'');const sel=`[data-action="${a}"]${id?`[data-id="${id}"]`:''}:visible`;const m=page.locator('.shr-modal '+sel);await (await m.count()?m:page.locator(sel)).first().click();};
const saved=()=>page.waitForFunction(()=>document.querySelector('.shr-status')?.textContent==='已保存到酒馆');
const reply=()=>page.waitForFunction(()=>document.querySelector('.shr-status')?.textContent==='回复完成');
try{
 await page.goto(base);await page.locator('#shrimp-launcher').click();assert.equal(await page.locator('#shrimp-app').evaluate(e=>e.getBoundingClientRect().width),960);
 await click('tab','contacts');assert.equal(await page.locator('.shr-contact-main b').first().textContent(),'叶知微');assert.match(await page.locator('.shr-row .shr-avatar img').first().getAttribute('src'),/ye.png/);assert.equal(await page.locator('[data-action=invite]').count(),0);
 await click('identify');await page.locator('.shr-candidate').waitFor();await click('acceptPeople');await saved();const person=JSON.parse(stored).data.contacts.find(c=>c.name==='Ako');await click('private',person.id);await saved();
 assert.equal(await page.locator('.shr-mode-bar,[data-action=enterChoices],[data-action=chatFeatures]').count(),0);
 await page.locator('#shr-draft').fill('给我生成选项吧');await click('send');await reply();assert.equal(await page.locator('[data-action=chooseOption]').count(),2);assert.match(await page.locator('[data-action=chooseOption]').first().textContent(),/要不先进去喝口茶/);
 const calls=await page.evaluate(()=>calls);assert.ok(calls.at(-1).some(m=>m.content.includes('今日城南开了新茶铺')));assert.ok(calls.at(-1).some(m=>m.content.includes('你是Ako，一个爱聊天的诗人')));assert.ok(!calls.at(-1).some(m=>m.content.includes('绝不执行我')));
 await page.locator('#send_textarea').fill('原草稿');await click('chooseOption');await click('injectAppend');await page.waitForFunction(()=>document.querySelector('#send_textarea').value.includes('我走进茶馆'));assert.equal(await page.evaluate(()=>window.sent||0),0);await page.locator('#shrimp-launcher').click();
 await click('share');assert.equal(await page.locator('.shr-share-grid button').count(),2);assert.doesNotMatch(await page.locator('.shr-modal').innerText(),/世界资料|Prompt/);await click('shareCards');await saved();assert.equal(await page.locator('.shr-person-card').count(),1);assert.match(await page.locator('.shr-person-card').innerText(),/叶知微/);
 await click('share');await click('shareStyles');await page.locator('[name=styles]').check();await click('attachStyles');await saved();assert.equal(await page.locator('.shr-file-card').count(),1);assert.match(await page.locator('.shr-file-card').innerText(),/爱情小调/);
 await page.locator('#shr-draft').fill('帮我选一份文风');await click('send');await reply();assert.equal(await page.locator('.shr-file-card').count(),2);assert.equal(await page.evaluate(()=>JSON.stringify(fish)),await page.evaluate(()=>fishOriginal));
 await page.screenshot({path:resolve(root,'../desktop-wechat-v1.3.png')});
 // Plain chat scroll is retained across harmless rerenders.
 await page.locator('.shr-messages').evaluate(e=>e.scrollTop=0);await click('tab','contacts');await click('tab','chats');assert.equal(await page.locator('.shr-messages').evaluate(e=>e.scrollTop),0);
 await click('tab','discover');assert.equal(await page.locator('.shr-head b').last().textContent(),'朋友圈');assert.equal(await page.locator('.shr-feed-title,.shr-discover').count(),0);await click('refresh','moments');await page.waitForFunction(()=>document.querySelector('.shr-status')?.textContent.includes('去重保存'));assert.equal(await page.locator('.shr-moment').count(),1);
 await click('tab','chats');assert.equal(await page.locator('[data-action=publisherChat]').count(),1);await click('publisherChat','builtin-hk');await click('refresh','news');await page.waitForFunction(()=>document.querySelector('.shr-status')?.textContent.includes('去重保存'));assert.equal(await page.locator('.shr-news-message').count(),1);assert.equal(await page.locator('.shr-feed-title').count(),0);await click('openArticle');assert.match(await page.locator('.shr-article-page .shr-article').innerText(),/烧鹅/);await click('back');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(root,'../mobile-publisher-v1.3.png')});
 // Upward gesture at the bottom refreshes only once and stays in this account's message stream.
 const before=await page.evaluate(()=>calls.length);await page.locator('[data-pull-refresh=news]').evaluate(el=>{el.scrollTop=el.scrollHeight;el.dispatchEvent(new TouchEvent('touchstart',{bubbles:true,touches:[new Touch({identifier:1,target:el,clientX:150,clientY:600})]}));el.dispatchEvent(new TouchEvent('touchend',{bubbles:true,changedTouches:[new Touch({identifier:1,target:el,clientX:150,clientY:500})]}));});await page.waitForFunction(n=>calls.length===n+1,before);await page.waitForFunction(()=>document.querySelector('.shr-status')?.textContent.includes('去重保存'));assert.equal(await page.locator('.shr-news-message').count(),1);
 await click('back');await click('conversation',JSON.parse(stored).data.conversations[0].id);await page.screenshot({path:resolve(root,'../mobile-chat-v1.3.png')});await click('back');await click('tab','me');await click('settings');await page.locator('[name=customUrl]').fill(base);await page.locator('[name=customKey]').fill('test-key');await click('loadModels');await page.waitForFunction(()=>document.querySelector('[name=customModel]').options.length===2);await page.locator('[name=customModel]').selectOption('model-b');assert.equal(modelRequests,1);await click('saveSettings');await saved();assert.equal(JSON.parse(stored).data.settings.customModel,'model-b');
 // Current Tavern story/role changes are reflected directly, without file-like story headings.
 await page.evaluate(async()=>{context.characters.push({name:'花照影',avatar:'hua.png',description:'断虹剑仙'});context.characterId=1;context.name2='花照影';context.chatId='story-two';await emit('chat');});await click('tab','contacts');assert.equal(await page.locator('.shr-contact-main b').first().textContent(),'花照影');assert.match(await page.locator('.shr-row .shr-avatar img').first().getAttribute('src'),/hua.png/);await click('tab','discover');assert.equal(await page.locator('.shr-moment').count(),0);assert.doesNotMatch(await page.locator('.shr-content').innerText(),/story-two/);
 assert.equal(await page.evaluate(()=>JSON.stringify(preset)),await page.evaluate(()=>originalPreset));assert.deepEqual(errors,[]);console.log('PASS: WeChat layout, current role/avatar, automatic context+presets, preset options, cards/files, fishboard read-only, publisher conversations, inline article reading, story isolation, model discovery, mobile upward refresh, scroll retention');
}catch(e){await page.screenshot({path:resolve(root,'../wechat-failed.png')});throw e;}finally{await browser.close();server.close();}
